export type RegistrationStatus =
  | "draft"
  | "metadata_incomplete"
  | "evidence_pending"
  | "split_confirmation_pending"
  | "performer_confirmation_pending"
  | "undocumented"
  | "ready_for_submission"
  | "submitted"
  | "under_review"
  | "registered"
  | "rejected"
  | "amendment_required"
  | "disputed"
  | "superseded"
  | "withdrawn"
