-- Song Metadata Expansion V1

alter table musical_works
add column if not exists internal_code text,
add column if not exists catalogue_number text,
add column if not exists version_label text,
add column if not exists sub_genre text,
add column if not exists themes text,
add column if not exists tags text,
add column if not exists composer_names text,
add column if not exists lyricist_names text,
add column if not exists publisher_name text,
add column if not exists publisher_share numeric(5,2),
add column if not exists composer_split_total numeric(5,2),
add column if not exists lyric_split_total numeric(5,2),
add column if not exists split_sheet_status text default 'not_started',
add column if not exists copyright_claimant text,
add column if not exists copyright_year integer,
add column if not exists copyright_notice text,
add column if not exists copyright_pack_url text,
add column if not exists copyright_evidence_notes text,
add column if not exists copyright_submitted_at timestamp,
add column if not exists copyright_confirmed_at timestamp,
add column if not exists api_handle text,
add column if not exists usage_tag text,
add column if not exists education_subject text,
add column if not exists education_grade text,
add column if not exists content_theme text,
add column if not exists allowed_usage text,
add column if not exists license_status text default 'internal_review',
add column if not exists available_for_api boolean default false,
add column if not exists metadata jsonb default '{}'::jsonb;
