-- Patch Finance V2 commitment type constraint to include compatibility values
-- still used by the Phase 1 UI/service framework.

ALTER TABLE public.workspace_finance_commitments
  DROP CONSTRAINT IF EXISTS workspace_finance_commitments_commitment_type_check;

ALTER TABLE public.workspace_finance_commitments
  ADD CONSTRAINT workspace_finance_commitments_commitment_type_check
  CHECK (
    commitment_type IN (
      'cipc_annual_return',
      'samro_membership_fee',
      'capasso_admin_fee',
      'popia_compliance',
      'coida',
      'music_licensing',
      'other_compliance',
      'provisional_tax',
      'vat',
      'income_tax',
      'paye',
      'other_tax',
      'producer_payment',
      'session_musician_fee',
      'featured_artist_payment',
      'songwriter_share',
      'royalty_distribution',
      'contractor_payment',
      'other_contributor_obligation',
      'studio_booking',
      'mixing',
      'mastering',
      'artwork',
      'video_shoot',
      'rehearsal',
      'equipment_hire',
      'other_production',
      'dsp_distribution',
      'playlist_campaign',
      'pr_campaign',
      'social_ads',
      'radio_plugging',
      'launch_event',
      'content_creation',
      'release_campaign',
      'other_release_marketing',
      'office_rent',
      'internet',
      'utilities',
      'staff_salary',
      'admin_cost',
      'transport',
      'other_operations',
      'hosting',
      'cloud_storage',
      'ai_subscription',
      'daw_subscription',
      'design_software',
      'accounting_software',
      'software_subscription',
      'other_software_infrastructure',
      'contract_review',
      'company_secretarial',
      'legal_consultation',
      'dispute_resolution',
      'governance_admin',
      'other_legal_governance',
      'loan_repayment',
      'investor_reporting',
      'bank_charges',
      'funding_application',
      'financial_review',
      'other_finance_funding',
      'royalty_payable',
      'licensing_share',
      'profit_share',
      'collaborator_share',
      'other_revenue_sharing',
      'training',
      'business_development',
      'market_research',
      'partnership_development',
      'expansion_project',
      'other_growth_expansion',
      'other'
    )
  );
