export const EVIDENCE_AUDIT_EVENT_TYPES = [
  "EVIDENCE_CREATED",
  "EVIDENCE_UPDATED",
  "EVIDENCE_SUBMITTED",
  "EVIDENCE_VERIFIED",
  "EVIDENCE_REJECTED",
  "EVIDENCE_SUPERSEDED",
  "EVIDENCE_EXPIRED",
  "EVIDENCE_LINKED",
  "EVIDENCE_UNLINKED",
  "EVIDENCE_INCLUDED_IN_SUBMISSION",
  "EVIDENCE_REMOVED_FROM_SUBMISSION",
  "EVIDENCE_READINESS_CHANGED"
] as const

export type EvidenceAuditEventType =
  typeof EVIDENCE_AUDIT_EVENT_TYPES[number]
